### ISSUE TITLE
_overrideExtensionHandlers tries to write to read-only require.extensions

### ISSUE THREAD

**Issue by touzoku** [thlorenz/proxyquire#167]
Not sure how to isolate this problem, it appears only when I'm trying to use proxyquire from an atom editor plugin.

I call proxyquire like this:
```javascript
var espreePath = Object.keys(require.cache).find(function (key) {
        return key.endsWith(path.join('espree', 'espree.js'));
});
var espree = proxyquire(espreePath, {
        'acorn-jsx/inject': function acornJsxInject(acorn) {
          return acornVFEL(acornJSX(acorn), true);
        }
});
```

But it fails with:
```
Cannot assign to read only property '.js' of object '#<Object>' TypeError: Cannot assign to read only property '.js' of object '#<Object>'
    at./node_modules/proxyquire/lib/proxyquire.js:272:35
    at Array.forEach (native)
    at Proxyquire._overrideExtensionHandlers (./node_modules/proxyquire/lib/proxyquire.js:265:35)
    at Proxyquire._withoutCache (./node_modules/proxyquire/lib/proxyquire.js:175:39)
    at Proxyquire.load (./node_modules/proxyquire/lib/proxyquire.js:136:15)
```

Where line 272 of proxyquire.js is as follows:
```javascript
    require.extensions[extension] = function(module, filename) {
      // Override the require method for this module
      module.require = self._require.bind(self, module, stubs);

      return originalExtensions[extension](module, filename);
    };
  });

```

So it looks like `require.extensions['.js']` is read-only in atom editor environment. And it the use of it is deprecated too... I wonder how this could be fixed?

**Comment by touzoku** [comment]
Supposedly it is caused by [this code in atom editor](https://github.com/atom/atom/blob/910fbeee31d67eb711ec0771e7c26fa408c091eb/src/compile-cache.js#L231).

```javascript
Object.defineProperty(nodeRequire.extensions, extension, {
      enumerable: true,
      writable: false,
      value: function (module, filePath) {
        var code = compileFileAtPath(compiler, filePath, extension)
        return module._compile(code, filePath)
      }
})
```

I wonder if it could be fixed using a simple addition of `Object.defineProperty(require.extensions, extension, { writable: true });` in `_overrideExtensionHandlers` function.

**Comment by touzoku** [comment]
It is quite difficult to write a test for this, I'm probably not as good in JS... 

So apparently it is not just about writable vs non-writable. For some reason in atom, the `Object.getOwnPropertyDescriptor(require.extensions, extension)` returns a descriptor that does not contain neither `value`, nor `get`, nor `set` properties.

For example, when you try to access `require.extensions['.js']` — it returns `null`, even though the property exists and has its descriptor.
