### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by xduseko** [thlorenz/proxyquire#201]
It's somehow not working. Can you help?

![image](https://user-images.githubusercontent.com/9591957/39361247-da97e066-4a21-11e8-83fc-4659fe46d803.png)

a.js:
```js
var b = require('./b');

module.exports = function () {
	console.log('Hi!');
};
```

b.js:
```js
throw new Error('You sux!!!');
```

a-test.js:
```js
const proxyquire = require('proxyquire');

const a = proxyquire('./a', {'./b': null});

describe('a', function () {
	it('call', function () {
		a();
	});
});
````

result:
```
C:\Users\xduseko\IdeaProjects\engramo-integration\node_modules\proxyquire\lib\proxyquire.js:176
      throw moduleNotFoundError(path)
      ^

Error: Cannot find module './b'
    at createNotFoundError (C:\Users\xduseko\IdeaProjects\engramo-integration\node_modules\module-not-found-error\index.js:4:13)
    at Proxyquire._require (C:\Users\xduseko\IdeaProjects\engramo-integration\node_modules\proxyquire\lib\proxyquire.js:176:13)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\xduseko\IdeaProjects\engramo-integration\example\a.js:1:71)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Object.require.extensions.(anonymous function) (C:\Users\xduseko\IdeaProjects\engramo-integration\node_modules\proxyquire\lib\proxyquire.js:305:43)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at Proxyquire._withoutCache (C:\Users\xduseko\IdeaProjects\engramo-integration\node_modules\proxyquire\lib\proxyquire.js:215:12)
    at Proxyquire.load (C:\Users\xduseko\IdeaProjects\engramo-integration\node_modules\proxyquire\lib\proxyquire.js:129:15)
    at Object.<anonymous> (C:\Users\xduseko\IdeaProjects\engramo-integration\example\a-test.js:3:11)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at C:\Users\xduseko\IdeaProjects\engramo-server\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\xduseko\IdeaProjects\engramo-server\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (C:\Users\xduseko\IdeaProjects\engramo-server\node_modules\mocha\lib\mocha.js:514:10)
    at Object.<anonymous> (C:\Users\xduseko\IdeaProjects\engramo-server\node_modules\mocha\bin\_mocha:480:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

Process finished with exit code 1
```

**Comment by bendrucker** [comment]
Intended behavior, setting a module stub to null triggers a not found error.
