### ISSUE TITLE
Error thrown when proxying non existing file

### ISSUE THREAD

**Issue by adelura** [thlorenz/proxyquire#207]
Hi and thank you for such a great package!

I stumbled upon weird case. I have following setup:

foo.js
``` js
module.exports = {
  bar: 4
};
```

app.js
``` js
let proxyquire = require("proxyquire");

let foo = proxyquire("./foo.js", {
    "./no-exsisting.js": 3
});
```

**Problem**  Above code is throwing an error.

Whereas requiring named packages doesn't: 

app.js
``` js
let proxyquire = require("proxyquire");

let foo = proxyquire("./foo.js", {
    "no-exsisting": 3
});
```

I think that it's related to https://github.com/thlorenz/proxyquire/issues/58

Not sure if its a bug, but is there a way to workaround this? In my unit tests I require files dynamically during run-time - as per unit test those doesn't exist as the paths are fake and I don't create fake files for fake packages.

I'm actually surprised that it does try to require original file.

``` bash
Error: Cannot find module './no-exsisting.js' from 'C:\Users\<username>\Desktop\pro
xyquire'
    at Function.module.exports [as sync] (C:\Users\<username>\Desktop\proxyquire\no
de_modules\resolve\lib\sync.js:40:15)
    at Proxyquire._resolveModule (C:\Users\<username>\Desktop\proxyquire\node_modul
es\proxyquire\lib\proxyquire.js:137:20)
    at Proxyquire.<anonymous> (C:\Users\<username>\Desktop\proxyquire\node_modules\
proxyquire\lib\proxyquire.js:205:35)
    at Array.reduce (native)
    at Proxyquire._withoutCache (C:\Users\<username>\Desktop\proxyquire\node_module
s\proxyquire\lib\proxyquire.js:204:6)
    at Proxyquire.load (C:\Users\<username>\Desktop\proxyquire\node_modules\proxyqu
ire\lib\proxyquire.js:129:15)
    at Object.<anonymous> (C:\Users\<username>\Desktop\proxyquire\app.js:3:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by adelura** [comment]
I just realized that it doesn't solved my problem when I actually do require dynamically my non existing file:

app.js
``` js
let proxyquire = require("proxyquire");

proxyquire.noPreserveCache();

let foo = proxyquire("./foo.js", {
    "./no-exsisting.js": {}
});

console.log(foo());
```

foo.js
``` js
module.exports = function () {
    return require("./no-exsisting.js"));
};
```

**Comment by adelura** [comment]
Solved when added flag `@noCallThru` to stub

app.js
``` js
let proxyquire = require("proxyquire").noPreserveCache();
let stub = {};
stub["@noCallThru"] = true;

let foo = proxyquire("./foo.js", {
    "./no-exsisting.js": stub
});

console.log(foo());
```

foo.js
``` js
module.exports = function () {
    return require("./no-exsisting.js");
};
```
