### ISSUE TITLE
TypeError: myClass is not a constructor

### ISSUE THREAD

**Issue by doque** [thlorenz/proxyquire#240]
Hi, I'm currently facing this issue after a migration to ES6 modules:

```diff
-module.exports = StrategyBase;
+export default StrategyBase;
```

After this, my test fails:
```js
import proxyquire from 'proxyquire';
// snip
const StrategyBase = proxyquire('../../../src/strategy/strategy-base');
```
I receive this error message:

```
1) MyClass should throw an error on init:
     TypeError: MyClass is not a constructor
      at _callee$ (test/unit/strategy/my-class-spec.js:18:26)
      at tryCatch (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
      at new Promise (<anonymous>)
      at Context.<anonymous> (node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
```

After going back to ES5 `module.exports`, everything works. However I can't mix ES5/ES6 imports due do my babel configuration.

Any way to fix this?

**Comment by bendrucker** [comment]
```
const StrategyBase = proxyquire('../../../src/strategy/strategy-base');
```

This line makes no sense, what is it supposed to do? I don't think we have enough info here to help either, I can't see what MyClass is. An example project is probably the best way to get to a resolution here but I'm willing to take another guess if you can add more info.

**Comment by doque** [comment]
Sorry for the confusion, that was a copy & paste - MyClass and StrategyBase is the same.

**Comment by bendrucker** [comment]
Gotcha, still unclear what you are intending to do by using proxyquire without any stubs, but I'll take that as being a cut-down example for the sake of illustration.

Pretty certain you're seeing this when introducing babel because babel translates `export default foo` to `module.exports = {default: foo}` which means you'll need to change your requires. Babel also changes your `import` statements to `require(mod).default` if I remember correctly. Proxyquire is specifically intended for proxying `require` so you're hitting some dissonance there.

You can probably use this if you're looking for a drop-in solution:

https://www.npmjs.com/package/babel-plugin-add-module-exports

Let me know if this works and I can add it to the docs since this has been a common source of misunderstanding.
