### ISSUE TITLE
Proxyquire cannot stub non-object imports

### ISSUE THREAD

**Issue by ninjatronic** [thlorenz/proxyquire#46]
Say I have a module `options.coffee`...

``` coffeescript
module.exports = 'foo'
```

I want to stub it for a test...

``` coffeescript
describe '/lib/anotherModule', ->
  imports = {}
  before ->
    imports['./options'] = 'bar'
  beforeEach ->
    thing = proxyquire "#{process.cwd()}/lib/thing", imports
  it 'should be defined', ->
    thing.should.exist
```

This will fail in the before block, because Proxyquire cannot mock non-object exports. The error is:

```
    TypeError: Object.keys called on non-object
    at Function.keys (native)
    at fillMissingKeys (/Users/pete/kinvey/projects/cli/node_modules/proxyquire/lib/proxyquire.js:12:10)
    at Proxyquire._require (/Users/pete/kinvey/projects/cli/node_modules/proxyquire/lib/proxyquire.js:143:7)
    at require (module.js:380:17)
```

**Comment by raine** [comment]
I think it would be great if the README had at least one example for stubbing a module that exports a single function directly. It's such a common use-case.

**Comment by thlorenz** [comment]
@raine PRs welcome :)
