### ISSUE TITLE
Problems mocking fs module

### ISSUE THREAD

**Issue by alappe** [thlorenz/proxyquire#78]
I use proxyquire a lot while testing and all is working fine, except when I try to mock the `fs` module. The shortest example:

```javascript
var fsStub, proxyquire, subject;
proxyquire = require('proxyquire');
fsStub = null;

subject = proxyquire('./lib/worker/update', {
  fs: fsStub
});
```

Leads to:

```
/private/tmp/t/node_modules/proxyquire/lib/proxyquire.js:147
      throw moduleNotFoundError(path);
            ^
Error: Cannot find module 'fs'
    at createNotFoundError (/private/tmp/t/node_modules/proxyquire/node_modules/module-not-found-error/index.js:4:13)
    at Proxyquire._require (/private/tmp/t/node_modules/proxyquire/lib/proxyquire.js:147:13)
    at require (module.js:384:17)
    at Object.<anonymous> (/private/tmp/t/lib/worker/update.js:1:72)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/private/tmp/t/node_modules/proxyquire/lib/proxyquire.js:243:43)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

Am I missing something here?

proxyquire: v1.7.1
nodejs: v0.12.7

**Comment by bendrucker** [comment]
That's how proxyquire is meant to work. When you pass null as a stub, it simulates that module being unavailable.

**Comment by alappe** [comment]
Ah, dang… sorry! I meant to override it further down, but skipped it for now…
