### ISSUE TITLE
bug when trying to mock `date-now` module

### ISSUE THREAD

**Issue by jamestalmage** [thlorenz/proxyquire#82]
Minimal repro here: https://github.com/jamestalmage/proxyquire-datenow-bug

Output
```
TypeError: argument src is required
    at merge (/Users/jamestalmage/WebstormProjects/proxyquire-datenow-bug/node_modules/proxyquire/node_modules/fill-keys/node_modules/merge-descriptors/index.js:37:11)
    at fill (/Users/jamestalmage/WebstormProjects/proxyquire-datenow-bug/node_modules/proxyquire/node_modules/fill-keys/index.js:11:7)
    at fillKeys (/Users/jamestalmage/WebstormProjects/proxyquire-datenow-bug/node_modules/proxyquire/node_modules/fill-keys/index.js:18:10)
    at Proxyquire._require (/Users/jamestalmage/WebstormProjects/proxyquire-datenow-bug/node_modules/proxyquire/lib/proxyquire.js:151:7)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jamestalmage/WebstormProjects/proxyquire-datenow-bug/index.js:1:73)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jamestalmage/WebstormProjects/proxyquire-datenow-bug/node_modules/proxyquire/lib/proxyquire.js:243:43)
    at Module.load (module.js:355:32)
```

It throws before the assertion is ever run.

This fixes it:
```
var proxyquire = require('proxyquire').noCallThru();
```

But I don't see why it's required to use `noCallThru()` here.

**Comment by bendrucker** [comment]
So apparently `Date.now` doesn't have a prototype

![The More You Know](http://i.ytimg.com/vi/GD6qtc2_AQA/sddefault.jpg+)

**Comment by jamestalmage** [comment]
LOL.

I'm stealing that.
